name: Debian packages release

on:
  workflow_dispatch:
    inputs:
      mode:
        required: true
        type: choice
        description: Type of release
        options: 
        - stable
        - testing
      dry_run:
        required: true
        type: boolean
      checkbox-ng:
        type: boolean
        required: true
      checkbox-support:
        type: boolean
        required: true
      provider-base:
        type: boolean
        required: true
      provider-resource:
        type: boolean
        required: true
      provider-tpm2:
        type: boolean
        required: true
      provider-sru:
        type: boolean
        required: true
      provider-certification-client:
        type: boolean
        required: true
      provider-certification-server:
        type: boolean
        required: true
      provider-gpgpu:
        type: boolean
        required: true
      provider-ipdt:
        type: boolean
        required: true
      provider-phoronix:
        type: boolean
        required: true

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Save the config options
        run: |
          echo '${{ inputs.config }}' | jq > config.json
      - name: Archive the release configuration
        uses: actions/upload-artifact@v3
        with:
          name: config.json
          path: config.json
      - name: Install dependencies
        run: |
          sudo apt -qq update
          sudo apt install -qq -y bumpversion python3-launchpadlib
          git clone https://git.launchpad.net/~checkbox-dev/checkbox/+git/support
      - name: Checkout checkbox monorepo
        uses: actions/checkout@v3
        with:
          repository: canonical/checkbox-staging
          fetch-depth: 0
          path: src/checkbox
      - name: Check for new commits
        run: |
          support/release/git/release_deb_monorepo.py clone --config config.json
      - name: Bump versions
        run: |
          git config --global user.email "sylvain.pineau@canonical.com"
          git config --global user.name "Sylvain Pineau"
          support/release/git/release_deb_monorepo.py bump --part major
      - name: Create changelog
        run: |
          support/release/git/release_deb_monorepo.py changelog
      - name: Archive changelog
        uses: actions/upload-artifact@v3
        with:
          name: Changelog
          path: changelog
      - name: Push release tags
        run: |
          support/release/git/release_deb_monorepo.py push
